---
development:
  cloud_name: dgql7hcka
  api_key: '942426317678272'
  api_secret: Sx3C-lsDQWnzYIFr7higsAXD174
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dgql7hcka
  api_key: '942426317678272'
  api_secret: Sx3C-lsDQWnzYIFr7higsAXD174
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dgql7hcka
  api_key: '942426317678272'
  api_secret: Sx3C-lsDQWnzYIFr7higsAXD174
  enhance_image_tag: true
  static_file_support: false
